// <auto-generated />
using System;
using Funemployment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Funemployment.Migrations
{
    [DbContext(typeof(FunemploymentDbContext))]
    partial class FunemploymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Funemployment.Models.Answer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BQID");

                    b.Property<string>("Content");

                    b.Property<DateTime>("Date");

                    b.Property<int>("PID");

                    b.Property<int?>("PlayerID");

                    b.Property<int>("TQID");

                    b.HasKey("ID");

                    b.HasIndex("PlayerID");

                    b.ToTable("AnswerTable");
                });

            modelBuilder.Entity("Funemployment.Models.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About");

                    b.Property<string>("Location");

                    b.Property<int>("Points");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("PlayerTable");
                });

            modelBuilder.Entity("Funemployment.Models.Answer", b =>
                {
                    b.HasOne("Funemployment.Models.Player")
                        .WithMany("MyAnswers")
                        .HasForeignKey("PlayerID");
                });
#pragma warning restore 612, 618
        }
    }
}
